### ISSUE TITLE
Too many "DELETEME" create and query requests cause mysql meta store hang infinitely

### ISSUE THREAD

**Issue by ericsahit** [datanucleus/datanucleus-rdbms#101]
Hi, 

we encounter this problem described below in our proc hadoop cluster, and thought it related with datanucleus used in hive.

Sometimes hive mysql metastore hang because of deadlock, so result in all hive client hanging infinitely.

We check in this problem, found most mysql request hang on " SHOW FULL COLUMNS FROM `DELETEME1472008582981` FROM `hive` LIKE '%'   "

More interesting is mysql request span to multiple nodes(up to 5) will request probe table with exactly same name, like below:

| 5409551 | hive    | 10.93.xx.54:23327   | hive | Query       |  1476 | Waiting for table metadata lock | SHOW FULL 
COLUMNS FROM `DELETEME1472008582981` FROM `hive` LIKE '%'                                  |
| 5409557 | hive    | 10.93.xx.20:3862    | hive | Query       |  1473 | Waiting for table metadata lock | SHOW FULL 
COLUMNS FROM `DELETEME1472008582981` FROM `hive` LIKE '%'                                  |
| 5409567 | hive    | 10.93.xx.51:48055   | hive | Query       |  1469 | Waiting for table metadata lock | SHOW FULL 
COLUMNS FROM `DELETEME1472008582981` FROM `hive` LIKE '%'                                  |
| 5409576 | hive    | 10.93.xx.32:18886   | hive | Sleep       |  1464 |                                 | NULL      
                                                                                           |
| 5409577 | hive    | 10.93.xx.32:18887   | hive | Query       |  1463 | Waiting for table metadata lock | SHOW FULL 
COLUMNS FROM `DELETEME1472008582981` FROM `hive` LIKE '%'                                  |
| 5409587 | hive    | 10.93.xx.32:19582   | hive | Query       |  1457 | Waiting for table metadata lock | SHOW FULL 
COLUMNS FROM `DELETEME1472008582981` FROM `hive` LIKE '%'   

obviously it is not identical with the datanucleus code in : `RDBMSStoreManager.java`, which one hive session will create probeTable with current milliseconds("DELETEME+system.currentMilliSeconds"). List above shows that five hive session among multiple node however request for ProbeTable with exactly same name!

And also we check our configuration related with datanucleus in hive-site.xml, autoCreateSchema(false) and fixedDataStore(true) has been set for long time. Code shows when these two properties is set, no "DELETEMExxx"(probe) table will be created and queried. So this confused us.

So we want to figure out why our hive client will request for such "DELETEMExxx" table, so result in deadlock in mysql metastore database.

Any suggestion will be welcome. Thanks!

env:

hive version: 1.2.1
datanucleus-core: 3.2.10
datanucleus-rdbms: 3.2.9
metastore database: MySQL
Local/Embedded Metastore Server
Hive user: 100+

**Comment by andyjefferson** [comment]
Kindly provide a valid testcase that demonstrates some problem, using the template in https://github.com/datanucleus/test-jdo

A DELETE_ME table is created ONCE at PMF startup to work out the schema name when it is not provided. Consequently for you to have MANY can only be the result of your code. Demonstrating this is in a testcase will resolve how this is happening

**Comment by ericsahit** [comment]
Hi @andyjefferson ,

Thanks for your reply.

We just encounter this phenomenon twice for three month. So i thought it was triggered by High concurrency requests. So i cannot find a way to repeat this problem.

And what confuse me is we should not allow such DDL operation in all of our hive clients:

1) Why the hive clients still create and search DELETE_ME after `fixedDataStore` has been set to true. Is there some usage of DELETE_ME not included in `RDBMSStoreManager.java`?
 
2) Why the hive clients span to multiple nodes(up to 5) will request DELETE_ME table with exactly same name?

could you help me to `explain these phenomenon` because i thought obviously this behaviour is not `identical` with the datanucleus code.

**Comment by andyjefferson** [comment]
"datanucleus.fixedDatastore" was removed after v3.3, and besides which would never apply to the DELETEME table, which is only to work out what your schema name is (because you didn't bother supplying it). Answer : supply the schema/catalog name in your configuration and then it likely won't need to work it out

**Comment by andyjefferson** [comment]
You can find the code where this is used at https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/RDBMSStoreManager.java#L1441  and then debug it yourself from there
