### ISSUE TITLE
Datanucleus MSSQLServerAdapter generates incorrect syntax for OFFSET-FETCH clause

### ISSUE THREAD

**Issue by vaibhavgumashta** [datanucleus/datanucleus-rdbms#110]
We're seeing an issue in Apache Hive with DN RDBMS version 4.x, MSSQLServerAdapter. The root cause is in `MSSQLServerAdapter#getRangeByLimitEndOfStatementClause` method. When DN tries to apply the OFFSET-FETCH clause, it uses an incorrect syntax (https://technet.microsoft.com/en-us/library/gg699618(v=sql.110).aspx):

1. It applies the OFFSET clause irrespective of whether there is an ORDER BY in the sql query. Per the linked doc, that's an incorrect syntax.
2. When the fetch size is 1, it uses FETCH NEXT ROW ONLY, which is incorrect syntax per the linked doc. The correct syntax is: FETCH NEXT 1 ROW ONLY.

As an example, this is a query generated in Hive by DN MSSQLServerAdapter: 

`SELECT 'org.apache.hadoop.hive.metastore.model.MStorageDescriptor' AS NUCLEUS_TYPE,A0.INPUT_FORMAT,A0.IS_COMPRESSED,A0.IS_STOREDASSUBDIRECTORIES,A0.LOCATION,A0.NUM_BUCKETS,A0.OUTPUT_FORMAT,A0.SD_ID FROM SDS A0 WHERE A0.CD_ID = ? OFFSET 0 ROWS FETCH NEXT ROW ONLY`

As you can see, the syntax is incorrect. 

I have a patch with the fix which I've tested with Hive. I'll create a pull request shortly.

**Comment by vaibhavgumashta** [comment]
Apache Hive jira where I'll upload a short term workaround for Hive: https://issues.apache.org/jira/browse/HIVE-14698.

**Comment by vaibhavgumashta** [comment]
The same issue exists in master branch as well.

**Comment by andyjefferson** [comment]
Dup of #107 and #108
