### ISSUE TITLE
If we have generic (abstract) root class, then abstract subclass specifying generic type, then concrete class fails to pick up the override of generic type

### ISSUE THREAD

**Issue by andyjefferson** [datanucleus/datanucleus-rdbms#115]
The root metadata has the generic type, so thinks the type of the member is Serializable. 
The sub abstract class metadata has an override of the root member, specifying the type as Long.
The sub-sub concrete class metadata has no override of the root member.

When generating the schema it currently just looks at the concrete type for the override, and not further up the tree.

**Comment by chrisco484** [comment]
Did this affect 4.x as well or was it only affecting 5.x?

**Comment by andyjefferson** [comment]
Every release, ever.
