### ISSUE TITLE
Allow user to override set distinct on jdo queries w/ implicit joins

### ISSUE THREAD

**Issue by djerraballi** [datanucleus/datanucleus-rdbms#124]
## Feature Request: provide as much detail as possible about behaviour
Many SQL datastores take a performance hit when running a query w/ a distinct clause. If a user's application can determine that their queries guarantee distinct results without the distinct clause, the application could receive a performance benefit by having that clause removed. 

https://github.com/datanucleus/datanucleus-rdbms/pull/123

**Comment by djerraballi** [comment]
#123

**Comment by andyjefferson** [comment]
Pull request applied. Thx
