### ISSUE TITLE
Constraints with Postgres

### ISSUE THREAD

**Issue by prquinlan** [datanucleus/datanucleus-rdbms#133]
The attached example is using postgres 9.4, java 8 and the latest versions 5.0.1. 

We can run mvn datanucleus:schema-create and successfully create the schema. However, if we run that a second time, the constraints between the two tables are replicated. 

I am not sure where the fault lies, but it appears that DN is behaving as if these constraints are missing and re-adding each time. 
[constraintTest.zip](https://github.com/datanucleus/datanucleus-rdbms/files/544436/constraintTest.zip)

**Comment by andyjefferson** [comment]
5.0.3 is the "latest version" FWIW, but I'll direct you to https://github.com/datanucleus/datanucleus-rdbms/issues/132 which should fix that. JDBC drivers that don't provide info on catalog/schema in their FK constraints

**Comment by prquinlan** [comment]
Brilliant thanks. I was using 5.0.3 – a typo sorry. Is 5.0.4 due soon?

Thanks,

Phil
