### ISSUE TITLE
Deployment of 5.0.4 on central.maven.org broke

### ISSUE THREAD

**Issue by prquinlan** [datanucleus/datanucleus-rdbms#136]
## Bug Report, attach a testcase using [problem guide]
The pom is missing from the deployed version 5.0.4 on:
http://central.maven.org/maven2/org/datanucleus/datanucleus-rdbms/5.0.4/

**Comment by andyjefferson** [comment]
What is this ? http://central.maven.org/maven2/org/datanucleus/datanucleus-rdbms/5.0.4/datanucleus-rdbms-5.0.4.pom   Besides which all of that is out of our control, managed by Sonatype
