### ISSUE TITLE
SQL Server should emulate null precedence

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-rdbms#147]
Currently you pass through the null precedence handling i.e. "order by column asc nulls last" but SQL Server does not support that syntax. A workaround to emulate that behavior is to use "case when column is null then 1 else 0 end, column asc" and the other way round for inverse orderning respectively. You probably have that already implemented for e.g. MySQL and just need to enable that for SQL Server.

**Comment by andyjefferson** [comment]
MySQL uses "ISNULL" so not applicable. Anyway a (untested) solution is now implemented so if you can check it and let us know if it works, then can be applied to 4.x, thx

**Comment by beikov** [comment]
I get the following exception now: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'NUCORDER0'.

**Comment by beikov** [comment]
See my comment for a proper fix please: https://github.com/datanucleus/datanucleus-rdbms/commit/e2a18c97be2c4a17c7cf2f86836cbc28656603b2#commitcomment-19986169

**Comment by beikov** [comment]
The fix in the PR works for me
