### ISSUE TITLE
SQL Server datetime functions "hour","minute","second" don't work on date column

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-rdbms#148]
Apparently SQL Server complains about using these functions with a column of type "date". Can you add a cast to datetime like "date_part(hh, convert(datetime, column))" so that these functions also work with that type?

**Comment by andyjefferson** [comment]
GitHub master has an update for this. If it works for you then let me know and I'll put it on v4.x also

**Comment by beikov** [comment]
This works for me
