### ISSUE TITLE
Datanucleus uses "image" type for byte[] and Byte[] by default for SQL Server

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-rdbms#150]
So the "image" column type is IMO wrong and the default should actually be "VARBINARY". I am having trouble because columns with type "image" are not allowed in the order by clause.

**Comment by andyjefferson** [comment]
DataNucleus sets the default for a serializable java type to be LONGVARBINARY for all RDBMS (including SQLServer). I've now changed this in plugin.xml to be VARBINARY for SQLServer. LONGVARBINARY is an artificially supported type for SQLServer mapped to IMAGE (see SQLServerAdapter). Try current GitHub master and if it works fine then I'll put on 4.x also

**Comment by beikov** [comment]
This works too
