### ISSUE TITLE
Joined relations are fetched although no specified

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-rdbms#155]
I have a query like `SELECT d FROM Document d JOIN d.owner o GROUP BY o, d.prop1, d.prop2` which might not make much sense but the generated SQL is problematic.
The resulting SQL query contains all properties of the joined relation `owner` in the select clause, although I didn't specify `FETCH JOIN` but a simple `JOIN`. The group by the owner alias `o` results in a group by `id` which is totally right, but because of that, strict RDBMS like e.g. SQL Server complain about other properties of the `owner` relation not being in the group by.

**Comment by andyjefferson** [comment]
Is "d.owner" a 1-1/N-1 and hence defaulted to EAGER fetching? Do you have a test sample (the classes) that can be used to reproduce it?, and consequently, while I cant run against SQLServer, I can run against other datastores (e.g PostgreSQL, MariaDB, H2, Oracle) and the SQL ought to be the same (just that with SQLServer it complains about the SQL). 

FWIW QueryToSQLMapper is what generates the query, and compileSelect will be adding the FetchPlan to the select, so maybe the "solution" will be for the DatastoreAdapter to not allow select of related objects if using group by (or something).

**Comment by beikov** [comment]
This was indeed because of having EAGER fetching, thanks for the hint.
