### ISSUE TITLE
Query with multiple roots when using same type as candidate fails to register the alias of the secondary root

### ISSUE THREAD

**Issue by andyjefferson** [datanucleus/datanucleus-rdbms#159]
When we have JPQL with a FROM clause with a secondary root (DN extension), it is only registering the secondary root alias for lookups when it is of a different type to the candidate. Should always register it

**Comment by andyjefferson** [comment]
See core-170 for testcase. Generates SQL that I consider correct with this change

**Comment by andyjefferson** [comment]
Note that the comment in that file about "Hibernate issues 1 query, 2x left join, all successful" arguably means that Hibernate disobeys the JPA spec. To quote spec $4.4.4 "Path expression navigability is composed using “inner join” semantics.". DanaNucleus uses 2x inner join since it is following this spec.

**Comment by beikov** [comment]
Please forget the details about the comments. The testcase is mostly copied from an earlier testcase and I might have missed to remove comments or adapt them. Anyways, Eclipselink and Hibernate both support this kind of query.
