### ISSUE TITLE
Handling of MaxFetchDepth in navigation requests

### ISSUE THREAD

**Issue by martinreiland** [datanucleus/datanucleus-rdbms#189]
A migration from a different JDO implementation (intelliBO) to DataNucleus related in some scenarios to significant more select statements. Following analysis and proposal for a change was done:

 During analysis of performance and generated SQL statements, I found some different behaviour in generation of requests when navigating through the object graph. My current assumption is, that statements caused by navigation (calling a getter on a unloaded field, in our case mostly lists) does not evaluate the MaxFetchDepth setting.
A simple example looks like this (assuming maxfetchdepth = 3):

```
@PersistenceCapable
public class Person
{
  @PrimaryKey
  private int sn;

  @Persistent(mappedBy = "person")
  private List<Address> addressList;
  
  getter/setter...
}

@PersistenceCapable
class Address
{
  @PrimaryKey
  private int sn;
  
  @Column(name = "PERSON_SN")
  private Person person;

  @Column(name = "COUNTRY_SN")
  @Persistent(defaultFetchGroup = "true")
  private Country country;
  
  getter/setter...
}

@PersistenceCapable
class Country
{
  @PrimaryKey
  private int sn;
  private String code;
  
  getter/setter...
}
```

In this example we execute a JDO query on the person table (e.g. SN == 10). Taking the person object we call person.getAddressList().
The behvaviour in our IntelliBO implementation was the fetching of the addresses and the country in one select, because country is in the default fetch group:

```
getAddressList() --> SELECT * FROM Adress,Country WHERE Adress.PERSON_SN = 10....
adrdess1.getCountry() --> No select
...
```

The behaviour in DataNucleus is first fetching the addressList and on call of getCountry() method fetching the country:

```
getAddressList() --> SELECT * FROM Adress WHERE Adress.PERSON_SN = 10
adrdess1.getCountry() --> SELECT * FROM Country WHERE Adress.Adress_SN = 1
adrdess1.getCountry() --> SELECT * FROM Country WHERE Adress.Adress_SN = 2
....
```

As we have sometimes deep object graphs, this change has in some cases a heavy influence on the performance.
I did then a check of the JDO 3.1 specification, and as I understood the section 12.7.1 about the FetchPlan, the default fetch group and fetch depth settings should also effect the navigation.
Next step was an analyis of the source code:
In our case with list fields, I found the class FKListStore. In this class there a several calls to the method SQLStatementHelper.selectFetchPlanOfSourceClassInStatement, to generate the
SQL statements.

In the method getIteratorStatement, line 1521, I found that the max fetch depth is hardcoded set to 0.

```
class FKListStore
method getIteratorStatement

SQLStatementHelper.selectFetchPlanOfSourceClassInStatement(subStmt, stmtClassMapping, fp, subStmt.getPrimaryTable(), elementInfo[x].getAbstractClassMetaData(), 0);
```

So my main question is, why is here no evaluation of the max fetch depth? 

I tried then to use the max fetch depth of the fetch plan and created a new lib for testing. And the change caused the decrease of the SQL statements in our example.

`SQLStatementHelper.selectFetchPlanOfSourceClassInStatement(subStmt, stmtClassMapping, fp, subStmt.getPrimaryTable(), elementInfo[x].getAbstractClassMetaData(), fp.getMaxFetchDepth());
`

There are some other places where SQLStatementHelper.selectFetchPlanOfSourceClassInStatement is called, but I did only a check for FKListStore.
It would be great if some of the DataNucleus experts could have a look on this. If this change does not break anything else, it would improve the performance in my opinion in certain scenarios:

**Comment by andyjefferson** [comment]
JDO TCK, JPA1 TCK, and all DN testsuites pass so marking as complete. 

If wanting this backported to 5.0 then provide a pull request against that branch.
