### ISSUE TITLE
Column-naming: Either support 'special' characters or be strict and fail early.

### ISSUE THREAD

**Issue by andi-huber** [datanucleus/datanucleus-rdbms#235]
### Usability Enhancement

Using a hyphen `-` character when naming a column 
`@javax.jdo.annotations.Column(name="hallo-world")`
MySql (and possibly others too) expect, that we escape the column-name with a backtick character when passing SQL statements:
``SELECT `hallo-world` FROM ... ``
which I believe is not properly handled by DataNucleus yet.

The easy way out would be to early fail if @Column.name is used with special characters. The more convenient solution would be to properly escape column-names in SQL statements. 

Just to express in code, what we currently use as a workaround for this particular use-case:

In `org.datanucleus.store.rdbms.identifier.AbstractIdentifierFactory` ...

```java
public DatastoreIdentifier newColumnIdentifier(String javaName, boolean embedded, FieldRole fieldRole, boolean custom)
{
    DatastoreIdentifier identifier = null;
    String key = "[" + (javaName == null ? "" : javaName) + "][" + embedded + "][" + fieldRole; // TODO Change this to a string form of fieldRole
    identifier = columns.get(key);
    if (identifier == null)
    {
        if (custom)
        {
        	// If the user has provided a name (CUSTOM) so dont need to generate it and don't need a suffix
            String baseID = truncate(javaName, dba.getDatastoreIdentifierMaxLength(IdentifierType.COLUMN));

            //XXX PATCHED for mySQL
            if(baseID.contains("-") && (dba instanceof MySQLAdapter)) {
            	identifier = new ColumnIdentifier(this, "`"+baseID+"`");
            } else {
            	identifier = new ColumnIdentifier(this, baseID);
            }
        }
        else
        {
            String suffix = getColumnIdentifierSuffix(fieldRole, embedded);
            String datastoreID = generateIdentifierNameForJavaName(javaName);
            String baseID = truncate(datastoreID, dba.getDatastoreIdentifierMaxLength(IdentifierType.COLUMN) - suffix.length());
            identifier = new ColumnIdentifier(this, baseID + suffix);
        }
        columns.put(key, identifier);
    }
    return identifier;
}
```

Feel free to extend on this.

Cheers, Andi

**Comment by andyjefferson** [comment]
Thanks for the report. The provided "dirty hack" isn't the way to go. You should instead look at this method
https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/adapter/BaseDatastoreAdapter.java#L881

and override it in the adapter for MySQL
https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/adapter/MySQLAdapter.java

You can see a similar idea already used for SQLServer 
https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/adapter/SQLServerAdapter.java#L269

Then you can provide it as a PULL REQUEST for GitHub master.

**Comment by andi-huber** [comment]
Thanks Andy, I really appreciate it.
Cheers!
