### ISSUE TITLE
MySQL identifier quoting according to (MySQL) documentation

### ISSUE THREAD

**Issue by andi-huber** [datanucleus/datanucleus-rdbms#238]
From the mysql 5.7 docs:

> Permitted characters in unquoted identifiers: ASCII: [0-9,a-z,A-Z$_] (basic Latin letters, digits 0-9, dollar, underscore)

proposed enhancement to this commit ...
https://github.com/datanucleus/datanucleus-rdbms/commit/d70fd7cc6be3cc8d02c84ca37340906e4ac3882c#diff-792f734512ca5ba47a68b4d28208b230 

code snippet ...

```
private final static Pattern needsQuoting = 
		Pattern.compile("[[^0-9]&&[^a-z]&&[^A-Z]&&[^$_]]+"); 

private static boolean needsQuoting(String columnName) {
	 return needsQuoting.matcher(columnName).find();
}

private static void test(String columnName) {
	System.out.println(String.format("name: %s, needs quoting: %b", 
			columnName, 
			needsQuoting(columnName))	);
}

public static void main(String[] args) {
	test("Hell0_W$rld"); // needs quoting: false
	test("Hello-World"); // needs quoting: true
	test("$$__"); // needs quoting: false
}
```

**Comment by andyjefferson** [comment]
Pull request now applied. Marking as fixed. Thanks for the contribution.

**Comment by andi-huber** [comment]
Thanks!
