### ISSUE TITLE
JDOQL query fails when using reference to interface field, and implementations share table

### ISSUE THREAD

**Issue by chrisco484** [datanucleus/datanucleus-rdbms#243]
The attached test case:

[persistentInterfaceQueryFails.zip](https://github.com/datanucleus/datanucleus-rdbms/files/1666326/persistentInterfaceQueryFails.zip)

includes an image of the class diagram used to reproduce the problem.

Basically when multiple concrete classes extend an abstract class that implements a persistent interface queries on the relationship from a separate class to the persistent interface seem to fail if a filter is used.

It would appear as if DN is choosing the wrong column (multiple are created) when generating the _where_ clause for the filter in the query.

The test case dumps a summary of the columns and the records in the H2 DB for the class that is the candidate of the query.

The test case fails with more than one class extending FixedWingAircraft. By removing the AirbusA380 class (and it's metadata in package.jdo) and leaving the Boeing747 the test case will then succeed with no other code changes.

**Comment by andyjefferson** [comment]
Why a separate column for an IMPLEMENTATION of an interface? because that is how interface FIELDS are modelled, and how it has always been modelled http://www.datanucleus.org:15080/products/accessplatform_5_1/jdo/mapping.html#interface_one_one

It does not take into account if you have some artificial abstract class for the interfaces (use the abstract class in the relation instead of the interface?) and that abstract class is mapped on to the table that will hold the subclass implementations. i.e your SPECIFIC SITUATION (interface field, where all implementations are stored in one table) is not explicitly handled the way you want. No plans to support that (since you have the abstract class you could use to achieve the same end).

This zip puts your test into the DN testcase format, packages, etc and readable (removing that Wrapper stuff). It runs for me. Perhaps see what is different

[test.zip](https://github.com/datanucleus/datanucleus-rdbms/files/1667076/test.zip)

FWIW 
You have a relation there that is presumably BIDIRECTIONAL yet have no "mapped-by".


And NO this is **not** a "persistent interface". It is a field that is an interface. A "persistent interface" in JDO is where you MARK an interface class as being persistence-capable (so that the JDO provider can generate an implementation).

**Comment by chrisco484** [comment]
I fully understand and expect there to be a separate column for each class that implements the interface as interfaces can't have their own table and an RDBMS won't support an FK to a non existent table. Having multiple columns is the only efficient way to do it.. but that's not the problem here. 
I would have expected there be a single column required for each class that implements the interface regardless of whether that class is abstract or not - abstract classes can have tables so no trouble for an RDBMS having an FK referencing the table of an abstract class.
In my scenario a column is created for each concrete class that extends the abstract class that implements the interface. That (to my logic at least) is not necessary. It's not necessary in the case where there is no interface and a class has a reference to an abstract base class.
In any case the 'more than one column per interface implementor', while may be unnecessary is really only an efficiency thing except to the point where it may have a part in the incorrect query results. It seems like DN might write to once column but query a different one? Perhaps if there was only one column per interface implementation the ambiguity would dissappear for the code that generates the filter part of the query.

I'll have a look into why we didn't use a "mapped-by".

I'll also take a look at your amended test case.

**Comment by chrisco484** [comment]
I looked at your amended test case and can't see any material differences except yours does work and mine doesn't! Weird.

The schema created is the same but there is a very subtle difference in the values stored.

ATC table snapshots:
-----------------------
Mine:
atc_id,aircraft_airbus_a380_fixedwingaircraft_id_eid,aircraft_boeing747_fixedwingaircraft_id_eid,version,classid,controllers_fixedwingaircraft_id_oid,
-----------------------------------------------------------------------
1,null,1,1,827627375,null,
-----------------------------------------------------------------------

Yours:
atc_id,aircraft_boeing747_fixedwingaircraft_id_eid,aircraft_airbus_a380_fixedwingaircraft_id_eid,version,classid,controllers_fixedwingaircraft_id_oid,
-----------------------------------------------------------------------
1,1,null,1,827627375,null,
-----------------------------------------------------------------------

The values for the second and third columns are switched.

Mine stores the ref to the Boeing747 in the AirbusA380 column
Yours stores it in the correct column!

Mysteries of the universe part 194835 :)

**Comment by chrisco484** [comment]
i tried rearranging my package.jdo to match the ordering of yours but still fails.

There must be some other subtle difference.

**Comment by andyjefferson** [comment]
Firstly, an abstract class cannot have instances, so is ignored as far as the current interface handling, only concrete implementations are used. Secondly, there is no check to see if (concrete) implementations share a table (and hence could share a FK, using a discriminator). You'd have to extend capabilities if you wanted that. 

Ordering of which implementation comes first will simply be down to what order the implementations were found in, when initialising metadata, hence can vary.

**Comment by andyjefferson** [comment]
FYI, the difference in the tests is as follows. In your Metadata the A380 metadata is ordered first (A380, then Abstract, then Boeing), whereas in mine it is in "logical order" (i.e define abstract first, then A380, then Boeing). The only SQL that is different is the last query
`SELECT FROM mydomain.model.AirTrafficController WHERE aircraft == :a`

results in
yours :

> SELECT "a0"."atc_id","a0"."version","a0"."classid" 
> FROM "atc" "a0" 
> WHERE "a0"."classid" = 827627375 AND "a0"."aircraft_airbus_a380_fixedwingaircraft_id_eid" = 1

mine : 

> SELECT "a0"."atc_id","a0"."version","a0"."classid" 
> FROM "atc" "a0" 
> WHERE "a0"."classid" = 827627375 AND "a0"."aircraft_boeing747_fixedwingaircraft_id_eid" = 1

Namely it uses the incorrect FK of the InterfaceMapping for your case, so somewhere is not checking the type of the query parameter against the FK mapping.

**Comment by chrisco484** [comment]
Thanks for the fix Andy! I'm away for the Australia Day long weekend but can't wait to try it when I get back.

**Comment by chrisco484** [comment]
Is the 4.1.x branch still supported? If so any chance this one could be back ported to that?

**Comment by andyjefferson** [comment]
Nope. I don't have java 7. Was EOL long time ago.

**Comment by chrisco484** [comment]
No worries. I guess the day of migration to 5.x has arrived... :)

 

________________________________

**Comment by chrisco484** [comment]
5.1.6 works very well! Thanks.

In regards to 

> It does not take into account if you have some artificial abstract class for the interfaces (use the abstract class in the relation instead of the interface?). 

The test case was a minimalist form of the structure we had in the main app, enough to reproduce the issue. In the main app there are multiple class hierarchies with their own abstract class that implements the interface and we wanted a single relationship to the interface in preference to multiple relationships to the abstract implementors of that interface.

As it turns out the collections were only needed as a work around for the filtering not working on the reference from AirTrafficController -> IAircraft so we're able to remove those collections now.
