### ISSUE TITLE
Schema not set for sequences defined in JDO file metadata

### ISSUE THREAD

**Issue by siepkes** [datanucleus/datanucleus-rdbms#247]
Everything below is with DataNucleus 5.1.6 and PostgreSQL 9.6. Schema was configured by using the `javax.jdo.mapping.Schema` property.

For example using this annotation for a sequence:

```
@Sequence(name = "coreAssetSequence", datastoreSequence = "core_asset_seq", strategy = SequenceStrategy.CONTIGUOUS)
```

Results in this query (with correct schema name `melissan`):

```
211321 21:30:57,038 [RpcInvocationRequestHandler-15] DEBUG DataNucleus.Datastore.Native [] - SELECT nextval('melissan.core_asset_seq')
```

And this `.jdo` XML file:

```
<?xml version="1.0" encoding="UTF-8"?>
<jdo>
    <package name="nl.serviceplanet.melissan.server.core.model">
   	 	<sequence name="Relation.SearchKey" datastore-sequence="core_relations_searchkey" strategy="contiguous" allocation-size="1" />
   	 	<sequence name="Asset.SearchKey" datastore-sequence="core_assets_searchkey" strategy="contiguous" allocation-size="1" />
    </package>
</jdo>
```
Results in this query (with no schema defined):

```
11273 21:30:56,990 [RpcInvocationRequestHandler-15] DEBUG DataNucleus.Datastore.Native [] - SELECT nextval('core_assets_searchkey')
```

Notice the last one is missing the schema definition in front of the sequence.

We worked around it by explicitly configuring the schema on the JDBC driver:
```
core.jdbc.url=jdbc:postgresql_autogis://localhost:5432/postgres?currentSchema=melissan
```

**Comment by andyjefferson** [comment]
Using the artificially created test 
[rdbms-247.zip](https://github.com/datanucleus/datanucleus-rdbms/files/1970921/rdbms-247.zip)

with one sequence defined in annotations and one sequence defined in XML (and using the schema property) this gives
CREATE SEQUENCE "NUCLEUS1"."PERSON_SEQ_ANN" START WITH 1 INCREMENT BY 50 CACHE 1
CREATE SEQUENCE "NUCLEUS1"."PERSON_SEQ_XML" INCREMENT BY 1 CACHE 1

So you're doing something different. But then there is a reason why a testcase is asked for ;-)

**Comment by andyjefferson** [comment]
No testcase, so closing. Can be reopened if a valid testcase is provided, for example based on the one I provided that demonstrates it all working.
