### ISSUE TITLE
Exception thrown on dynamic schema updates if class has no attributes

### ISSUE THREAD

**Issue by andyjefferson** [datanucleus/datanucleus-rdbms#267]
See https://github.com/datanucleus/datanucleus-core/issues/287. 
To be specific this throws an exception like 

> java.lang.IllegalArgumentException: argment is null
>         at mydomain.model.FixedWingAircraft.dnProvideFields(FixedWingAircraft.java)
>         at org.datanucleus.state.StateManagerImpl.provideFields(StateManagerImpl.java:2510)
>         at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.checkForSchemaUpdatesForFieldsOfObject(RDBMSPersistenceHandler.java:667)
>         at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:118)
>         at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4551)
>         at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4528)
>         at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2025)
>         at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1868)
>         at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1723)
>         at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:712)
>         at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:738)

This only happens with datanucleus.rdbms.dynamicSchemaUpdates set to true (hence why it is calling RDBMSPersistenceHandler.checkForSchemaUpdatesForFieldsOfObject)

The original Groups.io report is at https://datanucleus.groups.io/g/main/message/57

**Comment by chrisco484** [comment]
Shouldn't the datanucleus.rdbms.dynamicSchemaUpdates option only affect interfaces? There are no interfaces in this model.

Unless it assumes that a class with no attributes should be treated as an interface?

**Comment by andyjefferson** [comment]
It affects anything at all, in principle i.e all classes go through that code. In reality the only mapping that will do anything relating to dynamic is interfaces using per implementation mapping.

**Comment by chrisco484** [comment]
In the method checkForSchemaUpdatesForFieldOfObjects:

```
    private void checkForSchemaUpdatesForFieldsOfObject(ObjectProvider sm, int[] fieldNumbers)
    {
        if (storeMgr.getBooleanObjectProperty(RDBMSPropertyNames.PROPERTY_RDBMS_DYNAMIC_SCHEMA_UPDATES).booleanValue())
        {
            DynamicSchemaFieldManager dynamicSchemaFM = new DynamicSchemaFieldManager((RDBMSStoreManager)storeMgr, sm);
            sm.provideFields(fieldNumbers, dynamicSchemaFM);
            if (dynamicSchemaFM.hasPerformedSchemaUpdates())
            {
                requestsByID.clear();
            }
        }
    }
```

should we conditionally check if fieldNumbers is null (appears to be null for a class with no attributes) and, if so, avoid calling sm.provideFields and the rest of the methods in that body?

**Comment by andyjefferson** [comment]
Of course. It calls that method saying "I'm going to persist this class and these fields. Are there any schema updates needed?". So put a check on (fieldNumbers == null || fieldNumbers.length == 0) and return if so.
