### ISSUE TITLE
Concurrency issue in JoinMapStore

### ISSUE THREAD

**Issue by aihuaxu** [datanucleus/datanucleus-rdbms#288]
## Bug Report, attach a testcase using [problem guide](http://www.datanucleus.org/documentation/problem_reporting.html) and state what version the problem occurs in. **THIS IS MANDATORY**. Any "Bug" without a testcase will be CLOSED.

it has concurrency issue which should use double checked locking. See the code here (https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/scostore/JoinMapStore.java#L669)

        if (getStmtLocked == null)
        {
            synchronized (this) // Make sure this completes in case another thread needs the same info
            {
                 if (getStmtLocked == null) { .   <=  this check should be added 
                       // see https://en.wikipedia.org/wiki/Double-checked_locking
               
                // Generate the statement, and statement mapping/parameter information
                SQLStatement sqlStmt = getSQLStatementForGet(ownerOP);
                getStmtUnlocked = sqlStmt.getSQLText().toSQL();
                sqlStmt.addExtension(SQLStatement.EXTENSION_LOCK_FOR_UPDATE, true);
                getStmtLocked = sqlStmt.getSQLText().toSQL();
                 }
            }
        } 
Otherwise, two threads could run into the synchronized block in sequence and reinitialize the protected structure twice. Here is the case:

Two threads wait inside getStmtLocked == null block since initially getStmtLocked is null
Thread_1 initializes getMappingParams and exit out synchronized block and continue
Thread_2 enters synchronized block and reinitialize getMappingParams. There is a short period that getMappingParams is empty and Thread_1 is trying to get the value from getMappingParams (or getMappingParams is just not thread-safe and invalid data is read when another thread is writing to it).

**Comment by andyjefferson** [comment]
Anybody who has an issue can demonstrate it as the template requests, and provide a pull request to fix it. Thx

**Comment by aihuaxu** [comment]
There is no way to provide a test case since it's a concurrency issue and you won't be able to reproduce it easily. I think it's very obvious to check the code to see the issue by following the instruction above.

**Comment by andyjefferson** [comment]
I think its very obvious that you are the person seeing this and the onus is on YOU to demonstrate and/or fix it. aka what "open source" is about. If you aren't going to contribute then, since nobody else is seeing a problem in their usage, then it gets closed. Can't get simpler

**Comment by aihuaxu** [comment]
I see. Sure. I will work on the issue then. Didn't know the policy for this project.

**Comment by chrisco484** [comment]
Sometimes with concurrency issues it's possible to insert delays or
specially crafted 'waits' to deliberately trigger a concurrency issue in
order to reproduce the bug and then provide that it is fixed (for that
scenario at least)

 

________________________________
