### ISSUE TITLE
Too long select item alias is shortened only for select item even when used in order by 

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-rdbms#298]
Consider a sample JPQL query like 

```
SELECT e.id AS DOCUMENTWITHDEEPSUBQUERYEMBEDDINGVIEW_OWNER_PARTNERDOCUMENT_NAME
FROM SomeEntity e
ORDER BY DOCUMENTWITHDEEPSUBQUERYEMBEDDINGVIEW_OWNER_PARTNERDOCUMENT_NAME ASC
```

This query is translated for PostgreSQL to
```
SELECT "e.id" AS "DOCUMENTWITHDEEPSUBQUERYEMBEDDINGVIEW_OWNER_PARTNERDOCUMENTK51X"
FROM SomeEntity e
ORDER BY "DOCUMENTWITHDEEPSUBQUERYEMBEDDINGVIEW_OWNER_PARTNERDOCUMENT_NAME" ASC
```

It seems the alias is shortened, but apparently this shortening isn't applied for the alias in the order by clause.
Here is your test case: [datanucleus-test.zip](https://github.com/datanucleus/datanucleus-rdbms/files/2195836/datanucleus-test.zip)

**Comment by andyjefferson** [comment]
Identifiers are truncated (by DataNucleus) when they exceed the database defined max length, since not all databases do the truncation for you, hence it would be best practice for a JPA provider to do this. Sadly use of result aliases in ordering didnt go through that code, now fixed.
