### ISSUE TITLE
SQLServer warning about FLOAT type not provided

### ISSUE THREAD

**Issue by stevespringett** [datanucleus/datanucleus-rdbms#304]
Datanucleus: 5.1.9
Microsoft JDBC Driver: sqljdbc4.jar

```
WARN [DataNucleus.Datastore] Default type for java type of java.lang.Float was previously jdbc-type=FLOAT but this is not provided by the JDBC driver! Please report this to the DataNucleus developers
WARN [DataNucleus.Datastore] Default type for java type of java.lang.Double was previously jdbc-type=FLOAT but this is not provided by the JDBC driver! Please report this to the DataNucleus developers
```

Likely related to #29 

Datanucleus is configured to create the schema on startup. Schema is created successfully and without the above warning. On every subsequent restart however, the warnings show up.

I'm not sure if there's a workaround or even if this is something to be concerned about. Looking for guidance.

**Comment by stevespringett** [comment]
I also tested with the latest 6.4 and 7.0 JDBC drivers with the same results.

mssql-jdbc-6.4.0.jre8.jar
mssql-jdbc-7.0.0.jre8.jar

**Comment by andyjefferson** [comment]
Your JDBC driver is limited in capabilities. As simple as that. 

You could provide a PR with SchemaTool "dbinfo" output for https://github.com/datanucleus/datanucleus-rdbms/tree/master/docs  which documents what those drivers handle.

You could also update the SQLServerAdapter to update what handling your database requires (either add a dummy FLOAT handler to the code like is done for other DatabaseAdapters, or change the default for your versions of drivers to not reference FLOAT) ... https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/adapter/SQLServerAdapter.java

**Comment by andyjefferson** [comment]
No apparent willingness to do any of the suggestions, so closing. This software is dependent on contributions, particularly when the only people who can be bothered to do anything don't have that database
