### ISSUE TITLE
Possibility to have dirty reads using PostgreSQL

### ISSUE THREAD

**Issue by yakovlevsv** [datanucleus/datanucleus-rdbms#309]
Now when you create a native query it leads to creating a transaction in PostgreSQL database even for simple non-transactional queries.

        EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("name", props);
        String q = "select * from users where id=1";

        EntityManager entityManager = entityManagerFactory.createEntityManager();
        entityManager.createNativeQuery(q, User.class).getSingleResult();
        entityManager.close();

        EntityManager entityManager = entityManagerFactory.createEntityManager();
        EntityTransaction transaction = entityManager.getTransaction();
        transaction.begin();
        entityManager.createNativeQuery(q, User.class).getSingleResult();
        entityManager.createNativeQuery(q, User.class).getSingleResult();
        transaction.commit();
        entityManager.close();

The same thing for  entityManager.createQuery()

PostgreSQL 9.5 logs

2018-12-18 10:57:01  user@test LOG:  execute <unnamed>: SHOW TRANSACTION ISOLATION LEVEL
2018-12-18 10:57:01  user@test LOG:  execute <unnamed>: BEGIN
2018-12-18 10:57:01  user@test LOG:  execute <unnamed>: select * from users where id=1
2018-12-18 10:57:01  user@test LOG:  execute S_1: COMMIT
2018-12-18 10:57:02  user@test LOG:  execute <unnamed>: SHOW TRANSACTION ISOLATION LEVEL
2018-12-18 10:57:02  user@test LOG:  execute <unnamed>: BEGIN
2018-12-18 10:57:02  user@test LOG:  execute <unnamed>: select * from users where id=1
2018-12-18 10:57:02  user@test LOG:  execute <unnamed>: select * from users where id=1
2018-12-18 10:57:02  user@test LOG:  execute S_1: COMMIT

**Comment by andyjefferson** [comment]
DataNucleus creates no "transaction". It gets a JDBC connection and commits it. If you want something different you get the code and contribute. This description does nothing to describe what behaviour is required

**Comment by yakovlevsv** [comment]
I haven't written that DataNucleus creates "transaction". As I see it, any request to PostgreSQL database using DataNucleus leads to a new transaction in postgre. Moreover, for some reason it manipulates JDBC connection state. For example, it changes connection autocommit flag to false and any query execution without transaction becomes impossible.

**Comment by andyjefferson** [comment]
No test provided to demonstrate anything (as per the reporting template), so closing. Can be reopened if bothering to follow the established procedures, or alternatively provide whatever "fix" this needs with a clear description of why it is needed (and that it won't affect anyone else's use).
