### ISSUE TITLE
Handling MySQL's lower_case_table_names gracefully?

### ISSUE THREAD

**Issue by arsenyspb** [datanucleus/datanucleus-rdbms#310]
Hello dear colleagues,
Happy New Year!

Is there a way to handle the following exception caused by MySQL's `lower_case_table_names` by Datanucleus?..

I recently realized that `datanucleus-rdbms-4.1.19.jar`  throws an exception when is used with Azure Database for MySQL:

```
org.datanucleus.exceptions.NucleusUserException: Table "columns_v2" has been specified with a primary-key to include column "COLUMN_NAME" but this column is not found in the table. Please check your <primary-key> column specification. 
at org.datanucleus.store.rdbms.table.ElementContainerTable.applyUserPrimaryKeySpecification(ElementContainerTable.java:215) 
at org.datanucleus.store.rdbms.table.CollectionTable.initialize(CollectionTable.java:235) 
at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.initializeClassTables(RDBMSStoreManager.java:3260)
```
...because there is a difference in the way default deployment of MySQL 5.7.21 (...which is the one under the hood) looks like on Azure Database for MySQL and i.e. when it's installed on Ubuntu or via Docker. You can see the visualization [here](http://www.mergely.com/MTxLDN12/):  In nutshell, it's because of:

```
mysql> SHOW VARIABLES like "lower_case_table_names";
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| lower_case_table_names | 1     |
+------------------------+-------+
1 row in set (0.10 sec)
```
You may find our documented workaround [here](https://docs.azuredatabricks.net/user-guide/advanced/external-hive-metastore.html) : "_To use Azure Database for MySQL as an external metastore, you must change the value of the `lower_case_table_names` property from 1 (the default) to 2 in the server-side database configuration._"

Is there any possible solution to include this in the Datanucleus RDBMS so there's no workaround needed?..

**Comment by andyjefferson** [comment]
No idea what you refer to. All RDBMS define support for particular casing of identifiers and DataNucleus reads this from the JDBC driver and puts it in the log. You have `datanucleus.identifier.case` available to set to what you want to use, as per http://www.datanucleus.org:15080/products/accessplatform_5_2/jdo/mapping.html#datastore_identifiers

**Comment by andyjefferson** [comment]
No test provided to demonstrate anything (as per the reporting template), so closing. Can be reopened if bothering to follow the established procedures, or alternatively provide whatever "fix" this needs with a clear description of why it is needed (and that it won't affect anyone else's use).

**Comment by mybu** [comment]
@andyjefferson did you resolved this problem?

**Comment by andyjefferson** [comment]
What "problem"? Raiser was asked to demonstrate what was meant. Nothing happened. If something was "fixed" it would have a GitHub commit linked in the issue.

**Comment by mybu** [comment]
"Table 'columns_v2' has been specified with a primary-key to include column 'COLUMN_NAME' but this column is not found in the table. Please check your <primary-key> column specification" also happend in my environment（hive 2.1.1 + mysql 8 community server）.
when i enter in this page ,i think this problem appeared again.

**Comment by andyjefferson** [comment]
Second user quotes some error message without any way of reproducing it, and expects some sort of psychic powers to guess what they were doing. Problem reporting is well defined, https://www.datanucleus.org/documentation/problem_reporting.html

**Comment by arsenyspb** [comment]
We ended up documenting the workaround here https://docs.microsoft.com/en-us/azure/databricks/data/metastores/external-hive-metastore regarding lower_case_table_names , not ‘graceful’ but by restarting MySQL on Azure it worked.
