### ISSUE TITLE
Set Variables in mysql not supported

### ISSUE THREAD

**Issue by swaminathan-b** [datanucleus/datanucleus-rdbms#323]

**Comment by swaminathan-b** [comment]
You have specified an SQL statement ("SET FOREIGN_KEY_CHECKS=0") that doesnt start with SELECT. This is invalid.
org.datanucleus.exceptions.NucleusUserException: You have specified an SQL statement ("SET FOREIGN_KEY_CHECKS=0") that doesnt start with SELECT. This is invalid.

**Comment by andyjefferson** [comment]
DataNucleus does not issue any such SQL statement. Suggest that you check your facts, and also follow the problem reporting process next time (aka provide a testcase that demonstrates it)
