### ISSUE TITLE
PostgreSQL: failure to getObjectById() etc when connected to hot standby due to transaction isolation set to "serializable"

### ISSUE THREAD

**Issue by naknomum** [datanucleus/datanucleus-rdbms#336]
When connected to a PostgreSQL database in **hot standby** mode (e.g. secondary server in replication), the PostgreSQL exception below is thrown:

```
org.postgresql.util.PSQLException: ERROR: cannot use serializable mode in a hot standby
Detail: "default_transaction_isolation" is set to "serializable".
Hint: You can use "SET default_transaction_isolation = 'repeatable read'" to change the default.
```

A test case is basically _any attempt to **read an object**_ (e.g. with `getObjectById()`) from such a connection, the setup of [which](https://www.postgresql.org/docs/10/hot-standby.html) is beyond the scope of this bug report.

After much sleuthing, I have determined that the bug stems from `performTablesValidation()` [in RDBMSStoreManager.java](https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/RDBMSStoreManager.java#L3359), which in turn uses the private class [ClassAdder](https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/RDBMSStoreManager.java#L2869).

The problem arises because **ClassAdder** is constructed with the call `super(RDBMSStoreManager.this, dba.getTransactionIsolationForSchemaCreation());` and this _transaction isolation value_ ends up being set as `Connection.TRANSACTION_SERIALIZABLE` via [BaseDatastoreAdaptore.java](https://github.com/datanucleus/datanucleus-rdbms/blob/a62f9636d9ba3e969e2639e4570f76882ff20add/src/main/java/org/datanucleus/store/rdbms/adapter/BaseDatastoreAdapter.java#L1065).

As further evidence, the problem can be _resolved_ by simply **replacing** the _transaction isolation value_ in the ClassAdder constructor, for example, with `super(RDBMSStoreManager.this, TransactionIsolation.REPEATABLE_READ);`.  When this is done, `getObjectById()` etc will function as expected.

Not entirely sure the most sound path forward, but it seems like using `getTransactionIsolationForSchemaCreation()` may be misapplied here, as table validation is not _schema creation_.  But some way to alter the value getting passed here via ClassAdder is required in order to utilize hot standby enabled PostgreSQL instances.

**Comment by naknomum** [comment]
Added for reference.  From the **Section 26.5.5, Caveats** in the [PostgreSQL docs](https://www.postgresql.org/docs/12/hot-standby.html) (my emphasis):

> The **Serializable transaction isolation level** is not yet available in hot standby. (See Section 13.2.3 and Section 13.4.1 for details.) An attempt to set a transaction to the serializable isolation level in hot standby mode will **generate an error**.

**Comment by andyjefferson** [comment]
Since you are the only person with the problem then the "solution" is left for you to produce (via a Github pull request, thanks). This would logically be provide a persistence property (for the RDBMS plugin) that defines the transaction isolation level to use for schema creation. Default being what is there now.

Table "validation" is Schema validation, which is what the schema isolation level is for ... whether that is create, delete, update, validate. Nothing is "misapplied".
