### ISSUE TITLE
MySQL : Reserved word "RANK" not present with MySQL v8

### ISSUE THREAD

**Issue by bob71735** [datanucleus/datanucleus-rdbms#337]
Hi there. We're using `JDOPesistenceManager` API in `datanucleus-api-jdo` to persist our data object.(e.g `makePersistent()/makePersistentAll()`) and upgrading our database to mysql 8.
Unfortunately issue around reserved words conflict surface. (e.g. we have table with column name `rank`, which is also a reserved keyword in mysql 8). I believe the keywords fetched here are not complete.  
https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/adapter/BaseDatastoreAdapter.java#L288

It shouldn't hurt just quoting everything. Is it possible for you to 
1. Get all the keywords for post processing, **OR** 
2. Just add back ticks to escape all table and column names?

Looks like there was a similar issue on escaping https://github.com/datanucleus/datanucleus-rdbms/issues/235

**Comment by andyjefferson** [comment]
A better idea is for people to contribute improvements via github pull requests, which is why it is open source. Any changes to mysql keywords go in MysqlAdapter. Thx

**Comment by bob71735** [comment]
@andyjefferson I see. Thanks for quick response.

**Comment by andyjefferson** [comment]
Since the existing code explicitly calls DatabaseMetaData.getSQLKeywords() on the JDBC driver then you need to check why your JDBC driver is allegedly not returning that keyword in the keywords list. The source code for the MySQL JDBC driver is at https://github.com/mysql/mysql-connector-j/blob/release/8.0/src/main/user-impl/java/com/mysql/cj/jdbc/DatabaseMetaData.java

**Comment by bob71735** [comment]
Hmm... interesting. We are using version 5.1.48 for the driver currently. Seems the keyword `RANK` is already there https://github.com/mysql/mysql-connector-j/blob/release/5.1/src/com/mysql/jdbc/DatabaseMetaData.java#L699, but unfortunately it still breaks the mechanism. Will check more if I get a chance. Thanks @andyjefferson

**Comment by andyjefferson** [comment]
No progress, and we don't have this MySQL hence nothing to be done.

**Comment by chrisco484** [comment]
> Hmm... interesting. We are using version 5.1.48 for the driver currently. Seems the keyword `RANK` is already there https://github.com/mysql/mysql-connector-j/blob/release/5.1/src/com/mysql/jdbc/DatabaseMetaData.java#L699, but unfortunately it still breaks the mechanism. Will check more if I get a chance. Thanks @andyjefferson

Have you tried connecting to MySQL 8 with the Connector J version 8?
