### ISSUE TITLE
MySQL Connector J/8: Datanucleus message says to report missing Numeric type

### ISSUE THREAD

**Issue by chrisco484** [datanucleus/datanucleus-rdbms#339]
This is not so much a bug report as the following of a request from a log message generated when we switched to MySQL Server 8 and Connector J/8.

Message was:

[WARN ] 20:06:58.449 Datastore - Default type for java type of java.math.BigInteger was previously jdbc-type=NUMERIC but this is not provided by the JDBC driver! **_Please report this to the DataNucleus developers_**

So far, from our testing with MySQL Server 8 there doesn't seem to be any functionality issues so definitely doesn't seem like a bug - just a warning with a request to report it to the devs (which, I know, is most of us ;) )

**Comment by andyjefferson** [comment]
You mean that MySQL dropped support for the NUMERIC type? because it always used to support it.
Provide the output of DataNucleus SchemaTool "dbinfo" mode, just like you can find in https://github.com/datanucleus/datanucleus-rdbms/tree/master/docs
and provide a Pull Request to add it into that directory (the naming convention for the filename should be logical from looking at the others), otherwise just attach the file here.

**Comment by chrisco484** [comment]
I wonder if that's a bug/oversight in MySQL's version 8 Connector J JDBC driver?

They seem to be giving mixed messages in their doco on this page:

https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-type-conversions.html

This table: _Table 6.1 Possible Conversions Between MySQL and Java Data Types_ lists NUMERIC

This table: _Table 6.2 MySQL Types and Return Values for ResultSetMetaData.GetColumnTypeName()and ResultSetMetaData.GetColumnClassName()_ does not list NUMERIC! Huh?


This class which is meant to list all of its JDBC types still contains NUMERIC:

https://docs.oracle.com/javase/8/docs/api/java/sql/Types.html

I guess this is a case of the code being the only accurate documentation - unless it's an oversight on their behalf that they plan to fix it soon.

I can't find a single instance of BigInteger in our code base - the 64 bit 'long' is more than adequate until we need the ability to store a unique ID for every atom in the universe :)

**Comment by chrisco484** [comment]
It's interesting that Oracle's "other" product "Oracle Database" seemed to remove NUMERIC as well as reflected here by a DN change to the Oracle driver:

https://github.com/datanucleus/datanucleus-rdbms/issues/335

Maybe in the "We're more SQL standardized than you" race that Oracle/MySQL is having with Postgres (the SQL standard "leaders") NUMERIC has become collateral.

**Comment by andyjefferson** [comment]
the difference with Oracle is that I have Oracle and can reproduce it. Hence why I ask for the SchemaTool dbinfo output to add to the docs area, for reference

**Comment by andyjefferson** [comment]
Nothing to do here, since no dbinfo output provided and I don't have this DB.
