### ISSUE TITLE
Rework handling of UUIDMapping in queries so that doesn't just map on to StringXXX

### ISSUE THREAD

**Issue by andyjefferson** [datanucleus/datanucleus-rdbms#343]
Whilst the main use-case of a UUIDMapping is to map on to a String, we could potentially use a converter and map it to binary data for example. The current query mechanism needs some mods to change this assumption and allow flexibility

**Comment by chrisco484** [comment]
I think Postgres even has a specific native type to store UUIDs in compact, binary form.
