### ISSUE TITLE
Support @CreateTimestamp/@UpdateTimestamp using field of type java.time.Instant

### ISSUE THREAD

**Issue by andyjefferson** [datanucleus/datanucleus-rdbms#351]
While we default to java.sql.Timestamp, we ought to allow the "more modern" java.time.Instant.

**Comment by chrisco484** [comment]
Not sure if this is related but... one issue I discovered with Java "Date" class and MySQL is that even though Date has 'millisecond' resolution it maps to a MySQL DATETIME (or TIMESTAMP -forget which one exactly) but then appears to only have 'second' resolution.

I had some scenarios where the millisecond resolution was required so I ended up just storing a 'long' and changed the setDate/getDate methods appropriately to set and get the value to/from the that long attribute.

I just read now in some MySQL docs that is it possible to obtain fractional second resolution with DATETIME using formatting like:

YYYY-MM-DD HH:MM:SS[.fraction]

but I'm not sure if that is supported by DataNucleus via some metadata/annotation setting.

In time I'd want to move to the Java 8 Time based classes.

**Comment by andyjefferson** [comment]
Look at https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/adapter/MySQLAdapter.java#L136.

**Comment by chrisco484** [comment]
Very cool! I wasn't aware of that option. Good to know!

**Comment by andyjefferson** [comment]
Specifically to get DN to create a column that MariaDB will persist millisecs to you have to add something like

`@Column(length=5)`

so that it creates the column as

`CREATETIME DATETIME(5) NULL`

otherwise it just creates it as type DATETIME and ignores millisecs.
