### ISSUE TITLE
Multi tenancy Tenant and TenantReadIds priority

### ISSUE THREAD

**Issue by spassignat** [datanucleus/datanucleus-rdbms#366]
Using mutitenancy features, I had to distinguish the transaction performing insert from the one doing read operations, because Tenant has a priority over TenantReadIds. 

It would be great to :
- merge tenant and tenant-read-ids and use them for all read operation, without looking at the tenant
- use tenant for create (insert) operation (actual behaviour)
- use the tenant of the object for update and delete operation (maybe an optional behaviour if the user prefers to only allow update and delete in the provided tenant (EntityManager/EntityManagerFactory)

**Comment by andyjefferson** [comment]
No idea what is "merge tenant and tenant-read-ids". The DEFAULT behaviour that 99% of people will use is to use a single tenantId and use that for reads and writes. As a consequence it has to check whether a single value or multiple for what SQL is generated. No point creating an IN statement when using the default.

**Comment by spassignat** [comment]
That's a rational approach, which I'm not always agree with...


Maybe another solution is to have tenant-read-ids with tenant-create-id XOR tenant.

If tenant is present, then we just use it and that works like today and if tenant is null then we look at the tenant-create-id and tenant-read-ids.
