### ISSUE TITLE
entiry.getList().size() should not throw index out of bound exception

### ISSUE THREAD

**Issue by dcheung2** [datanucleus/datanucleus-rdbms#378]
For an entry using interface in a List, 

```
interface Food{}
class Apple extends Food{}
class Beef extends Food{}

class Menu{
  List<Food> food;
}
```

Expected behavior:

Actual behavior:
`menu.getFood().size()` or `menu.getFood().isEmpty()` on a store-backing-list could cause Exception at line 716
https://github.com/datanucleus/datanucleus-rdbms/blob/ade96252d17561683ffea919fd227c326502ad97/src/main/java/org/datanucleus/store/rdbms/scostore/ElementContainerStore.java#L716

Workaround:
`menu.getFood().iterator().hasNext();`
to convert the list to a cache-backed-list

**Comment by andyjefferson** [comment]
Still no testcase defined. Kindly provide one so that this is reproducible or it can be closed

**Comment by andyjefferson** [comment]
No way to reproduce, so closing
