### ISSUE TITLE
Bulk Delete with multiple joins fails with null pointer exception

### ISSUE THREAD

**Issue by yunus** [datanucleus/datanucleus-rdbms#379]
In a bulk delete with multiple joins, I get a null pointer exception. With single join it works fine.
I have encountered this problem with first  at  version 4.1 but I see that it is still valid. The [test case](https://github.com/yunus/test-jdo) that I provide runs on latest available release.

When I check logs, I see the error happens [here](https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/sql/DeleteStatement.java#L84).
```java
// Put any remaining joins into the sub-statement            
while (joinIter.hasNext()) {                
    SQLJoin join = joinIter.next();                
    subStmt.joins.add(join);     // --> subStmt.joins is null.       
}
```

I have tried to replace `subStmt.joins.add(join)` with native join addition feature `subStmt.addJoin(...)` but then I get other errors.
So as a temporary solution I simply instantiate the `joins` array just before the adding a new one.
```java
// Put any remaining joins into the sub-statement            
while (joinIter.hasNext()) {                
    SQLJoin join = joinIter.next();  
    if(subStmt.joins == null){
         subStmt.joins = new ArrayList<>();
    }              
    subStmt.joins.add(join);       
}
```

**Comment by andyjefferson** [comment]
Suggest that you try the change in 
https://github.com/datanucleus/datanucleus-rdbms/commit/dd745d9c2ab6424c3123bd74028839f67b520694
and report your findings
