### ISSUE TITLE
Index creation on multitenant "synthetic" column fails

### ISSUE THREAD

**Issue by spassignat** [datanucleus/datanucleus-rdbms#400]
Hello,

When a class is declared like this, index creation fails:

```
@Table(
	   indexes = {
			   @Index(name = "idx_tenant", columnList = "tenant"),
	   })
@MultiTenant(column = "tenant")

```

The failure is a wrong SQL syntax, the column to index is missing: 
`CREATE INDEX idx_pay_application_tenant ON pay_application ()`

I actually can't create a testcase, due to maven dependencies download failures. So here are some screen shots:

![image](https://user-images.githubusercontent.com/6451374/130477031-24024572-07a8-4213-ae12-3576203544a6.png)

Database has an index on the column (created manually):
![image](https://user-images.githubusercontent.com/6451374/130477190-f08e9562-869d-464a-add0-ee5cebdd9e0a.png)

**Comment by spassignat** [comment]
I created this pull request, let me know if it's fine (I'm really a beginner on github) : https://github.com/datanucleus/tests/pull/24

**Comment by andyjefferson** [comment]
Not testcase that reproduces anything with current code
