### ISSUE TITLE
Specification of column name in <primary-key> block doesnt use identifier case in checks

### ISSUE THREAD

**Issue by andyjefferson** [datanucleus/datanucleus-rdbms#409]
If we specify the column names in <primary-key> blocks (or equiv annotations) in lowercase and put the datanucleus.idenfier.case to be UPPERCASE then some checks don't use the specified name in identifier case, and cause schema failures in checks.

**Comment by kokila-19** [comment]
@andyjefferson We have been trying to upgrade datanucleus in hive and this change seems to problematic/wrong.
This line "String colName = this.storeMgr.getIdentifierFactory().getIdentifierInAdapterCase(pkCols[i].getName());" returns the column name with double quotes ("ID") and it does not match with mappings "this.ownerMapping.getColumnMapping(j).getColumn().getIdentifier().getName().equals(colName)".

This is the line which you changed and its creating trouble. This used to have quotes earlier and things used to work. Can you share some pointers on this ?

**Comment by andyjefferson** [comment]
There are many different databases, and they all have their own interpretation of an SQL standard. Consequently some add quotes, some don't. Some default to caps, some don't. Obviously I am not going to remember the details of this issue from 2.5 yrs ago. If you have a problem you need to use the problem reporting process with a valid testcase.

**Comment by kokila-19** [comment]
Okay, will do that.
Thanks !!
