### ISSUE TITLE
Dynamic Fetch Groups are being ignored

### ISSUE THREAD

**Issue by mores** [datanucleus/datanucleus-rdbms#435]
Test Case: https://github.com/mores/test-jdo/tree/dynamicFetch

When Fetch group is defined using annotation - query using detachCopyAll works just fine. ( testSimple )

When Fetch group is dynamically defined - fetch plan is ignored. ( testDynamic )

I can confirm this was working in 3.X

**Comment by andyjefferson** [comment]
**PMF scoped FetchGroups.**
If you call `getFetchGroup` on the PMF you get a new FetchGroup that is not active by default (as per JDO spec), unless one of that name already has been registered and is already active. To make a PMF-scoped fetch group _active_ you then need to call `pmf.addFetchGroup()` ... as per the JDO spec. 

**PM scoped FetchGroups**.
A PM scoped fetch group OTOH is active upon call to `getFetchGroup` and there is no such "addFetchGroup"/"removeFetchGroup" on the PM for making them "active".

What "v3" did (10 yrs ago) is of little interest to me.
