### ISSUE TITLE
Problem getting generated primary key with PostgreSQL and valueStrategy "IdGeneratorStrategy.IDENTITY"

### ISSUE THREAD

**Issue by jfirles** [datanucleus/datanucleus-rdbms#437]
This week I upgrade one of my projects that uses datanucleus to latest 5.x version and I have a problem with persisted classes with the valueStrategy = "IdGeneratorStrategy.IDENTITY".

When I persist an object with that primary key type I get an error from PostgreSQL:

```
Failed test : Insert of object "mydomain.model.Item@4f3bbf68" using statement "INSERT INTO "ITEMS" ("NAME") VALUES (?)" failed : ERROR: column ""ID"" does not exist
  Hint: Perhaps you meant to reference the column "ITEMS.ID".
  Position: 52
```

The query that causes the problem is like that (from PostgreSQL log):
```
INSERT INTO "ITEMS" ("NAME") VALUES ($1)
	RETURNING """ID"""
```

And this is a sample INSERT that works (inserted with psql client):
```
INSERT INTO "ITEMS" ("NAME") VALUES ('item 2') RETURNING "ID";
```
The sample project that reproduces the probles is here:
https://github.com/jfirles/test-jdo

**Comment by andyjefferson** [comment]
PostgreSQL has always required persistence property **datanucleus.identifier.case** setting to "lowercase".

**Comment by jfirles** [comment]
I never seen in the docs that PostgreSQL exception, I will search it. I tested with that persistence property and now it not fail.

The problem is that my current schema is generated with upper case words and it's in production.

I checked that the problems begins at version 5.2.9, the previous version (5.2.8) works ok. I searched the changelog for that version and I found that issue:
https://github.com/datanucleus/datanucleus-rdbms/issues/375

Is possible that the bug has introduced in that issue?

Best regards

**Comment by andyjefferson** [comment]
If some user (S. Springett) wants to make some comment on some other repo about what they think has happened on DataNucleus without actually mentioning their concerns to us then we aren't going to be aware of them.
Introduction of bugs is always possible due to tests being unable to cover all situations and only 1 person bothering to develop this.

**Comment by andyjefferson** [comment]
Made a change to datanucleus-rdbms on 5.2 branch to restrict that PR to Oracle. Suggest that you get the code from GitHub build it and try it.

**Comment by jfirles** [comment]
I'm tested and now works fine.

Thanks

**Comment by andyjefferson** [comment]
Marking as fixed. FWIW The PR was passing in a column name "raw" rather than the identifier name (quoted etc).
