### ISSUE TITLE
ConnectionFactoryImpl#closeAfterTransactionEnd returns always true

### ISSUE THREAD

**Issue by amirnajmi** [datanucleus/datanucleus-rdbms#445]
https://github.com/datanucleus/datanucleus-rdbms/blob/1788efc5d5b561f24d5efdfd93cd905e629ee150/src/main/java/org/datanucleus/store/rdbms/ConnectionFactoryImpl.java#L707

Hello there
May I ask you what is the reason for this line, as we can not use PROPERTY_CONNECTION_SINGLE_CONNECTION with this logic?

**Comment by chrisco484** [comment]
Hi @amirnajmi ,

The docs say:

> With a PM we normally allocate one connection for a transaction and close it after the transaction, then a different connection for nontransactional ops. This flag acts as a hint to the store plugin to obtain and retain a single connection throughout the lifetime of the PM. {true, false}

and the method you are looking at is called closeAfterTransactionEnd() - so with singleConnectionPerExecutionContext set to true the connection, according to the docs, should be "kept alive" so closeAfterTransactionEnd() should not be be closing the connection when the transaction ends. So the code seems to be doing exactly that.

**Comment by andyjefferson** [comment]
And QUESTIONS are to be asked in a SUPPORT FORUM / GROUP, not in an ISSUE TRACKER
