### ISSUE TITLE
Provide InitSQL hikari options

### ISSUE THREAD

**Issue by shinji62** [datanucleus/datanucleus-rdbms#466]
## Feature Request

I think this one should be an easy one, but I am not my self familiar with Datanucleus.
Hikari provide the options InitSQL which is very convenient we need to warmup DB [See here ](https://github.com/brettwooldridge/HikariCP/blob/HikariCP-3.4.5/src/main/java/com/zaxxer/hikari/HikariConfig.java#L375) 

I created a PR for the 5.2.X branch 

thanks

**Comment by shinji62** [comment]
cc @andyjefferson

**Comment by andyjefferson** [comment]
This was implemented in v6.0+ via issue #468. It is in GitHub/5.2 but no plans to release anything on 5.x so people can download and build themselves if they need it
