### ISSUE TITLE
keyword "COLUMN_NAME" for dm database

### ISSUE THREAD

**Issue by Freedom-Mr** [datanucleus/datanucleus-rdbms#473]
Introducing dm(达梦) database drivers，run sql：

INSERT INTO COLUMNS_V2 (CD_ID,COMMENT,"COLUMN_NAME",TYPE_NAME,INTEGER_IDX) VALUES (?,?,?,?,?) 

ERROR : FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:Add request failed : INSERT INTO COLUMNS_V2 (CD_ID,COMMENT,"COLUMN_NAME".....

org/datanucleus/store/rdbms/adapter/SQLConstants.java add "COMMENT" keyword

thanks

**Comment by andyjefferson** [comment]
There is no such file org/datanucleus/store/rdbms/adapter/SQLConstants.java. Perhaps you refer to BaseDatastoreAdapter.java.
https://github.com/datanucleus/datanucleus-rdbms/tree/master/src/main/java/org/datanucleus/store/rdbms/adapter

"COMMENT" is not a reserved keyword in SQL92, SQL99, SQL2003, nor on many RDBMS, but is apparently reserved on DB2 and Oracle. It should be added to the datastore adapters that need it only (and is already present for DB2 and Oracle). 
I've no idea what is this dm (chinese character) database, and we do not support it explicitly, but if it is to be supported (by you), you need to add the reserved word in its datastore adapter

**Comment by andyjefferson** [comment]
Closing since this "dm" database is not supported. if you want it supported you need to provide a GitHub Pull Request with the datastore adapter etc

**Comment by Freedom-Mr** [comment]
Okay, Thank you for your reply.
