### ISSUE TITLE
Unexpected query performance numbers in datanucleus log

### ISSUE THREAD

**Issue by mboapache** [datanucleus/datanucleus-rdbms#489]
Running a JDOQL query shows unexpected performance numbers in the datanucleus log.

The class SimpleTest runs an aggregate JDOQL query and tries to figure how much time is spend in the RDBMS versus in the JDOQL query layer. The query is executed on derby and on H2. The datanuclues logging output in datanuclues.log shows unexpected query execution times when comparing the two RDBMS. 

With derby the SQL execution time is a few millis and most of the time in spent in the JDOQL query layer:
14:52:54,997 (main) DEBUG [DataNucleus.Datastore.Native] - SELECT MAX(A0.X) FROM POINT A0 CROSS JOIN POINT VAR_P2 WHERE A0.X >= 0 AND VAR_P2.X >= 0
14:52:54,997 (main) DEBUG [DataNucleus.Datastore.Retrieve] - SQL Execution Time = 1 ms
14:53:02,086 (main) DEBUG [DataNucleus.Query] - JDOQL Query : Execution Time = 7087 ms

With H2 most of the  time is spent in the RDBMS:
14:53:12,505 (main) DEBUG [DataNucleus.Datastore.Native] - SELECT MAX(A0.X) FROM POINT A0 CROSS JOIN POINT VAR_P2 WHERE A0.X >= 0 AND VAR_P2.X >= 0
14:53:15,263 (main) DEBUG [DataNucleus.Datastore.Retrieve] - SQL Execution Time = 2757 ms
14:53:15,263 (main) DEBUG [DataNucleus.Query] - JDOQL Query : Execution Time = 2758 ms

Since the query returns a single non-persistent value I would expect that most of the time is spent in the RDBMS, 
such as in the case of H2. The performance numbers with derby are somewhat unexpected.

This seems unexpected to me, could you please take a look.  

Please see test-jdo fork at https://github.com/mboapache/test-jdo/tree/query-performance

**Comment by andyjefferson** [comment]
Not an issue for DN
