### ISSUE TITLE
Order metadata not populated for the list member

### ISSUE THREAD

**Issue by georgeghimici** [datanucleus/datanucleus-rdbms#53]
Hi everyone, we have a scenario where  sometimes the order metadata of a list member it's not populated. After a server application restart the error disappear and later can appear again.

**Error message:**

Class "LoanAccount" has collection field "funds" and this has no mapping in the table for the index of the element class "InvestorFund". Maybe you declared the field as a java.util.Collection and instantiated it as a java.util.List yet omitted the <order> element in the MetaData ? javax.jdo.JDOUserException: Class "LoanAccount" has collection field "funds" and this has no mapping in the table for the index of the element class "InvestorFund". Maybe you declared the field as a java.util.Collection and instantiated it as a java.util.List yet omitted the <order> element in the MetaData ? at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:636) at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:720) at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:740) 

**JDO models:**

@PersistenceCapable(detachable = "true", table = "GUARANTY")
@Discriminator(strategy = DiscriminatorStrategy.VALUE_MAP, column =   BaseSecurity.DISCRIMINATOR_COLUMN, value = "BASE_SECURITY")
public abstract class BaseSecurity implements Serializable {

	static final String DISCRIMINATOR_COLUMN = "DISCRIMINATOR";
	
	...
} 

@PersistenceCapable(detachable = "true")
@Discriminator(strategy = DiscriminatorStrategy.VALUE_MAP, column =     BaseSecurity.DISCRIMINATOR_COLUMN, value = "GUARANTY")
public class Guaranty extends BaseSecurity {

...

} 

@PersistenceCapable(detachable = "true")
@Discriminator(strategy = DiscriminatorStrategy.VALUE_MAP, column = BaseSecurity.DISCRIMINATOR_COLUMN, value = "INVESTOR_FUND")
public class InvestorFund extends BaseSecurity{

....

} 

@PersistenceCapable(detachable = "true")
public class LoanAccount {

    ...
        @Element(dependent = "true")
	@Persistent
	@Column(name = "GUARANTEES_ENCODEDKEY_OWN", target = "Guaranty")
	@Order(column = "GUARANTEES_INTEGER_IDX")
	private List<Guaranty> guarantees = null;
	
	@Element(dependent = "true")
	@Persistent
	@Column(name = "FUNDS_ENCODEDKEY_OWN", target = "InvestorFound")
	@Order(column = "FUNDS_INTEGER_IDX")
	private List<InvestorFund> funds = null;
    ...
} 

**Note**
Error is raised only for the funds field from the LoanAccount, never for the guarantees field

Any help is appreciated, thanks!

**Comment by andyjefferson** [comment]
Kindly use the "forum" for questions. 
Anything raised in the issue tracker has to have a valid testcase that reproduces the problem.

**Comment by georgeghimici** [comment]
Sure, thanks for your replay!
