### ISSUE TITLE
Clarification regarding connection pool sizes

### ISSUE THREAD

**Issue by nrg4878** [datanucleus/datanucleus-rdbms#57]
Apache uses data nucleus RDBMS libs (version 3.2.9), with BoneCP connection pooling (0.8.0-RELEASE). I am trying to find out what the default connection pool size is.
I dug around a bit in both data nucleus code and the BoneCP code and what I see in reality does not match the logic in the code.
Using "datanucleus.connectionpool.maxPoolSize" seems to have no effect on the max number of connections to the backend DB. Using "datanucleus.connectionpool.minPoolSize", the total number of connections to the backendDB are 2x the value set for this property.
I have played around with these values a little bit in number of different clusters in-house and the observations were consistent.
For example:
minPoolSize=10, maxPoolSize=15 total number to the backend DB was 20.
minPoolSize=20, maxPoolSize=30, total number of CNXS to backend DB was 40.
Without setting these values, I see the total number of CNXS to DB are 10.

In a different environment,
the default CNXS were 14.
when minPoolSize=12 and maxPoolSize=30, we observed a total of 42 connections to the backend DB.

Looking at the code neither behavior makes any sense.
https://github.com/datanucleus/datanucleus-rdbms/blob/4c056f392fa1673367a6ac4f494aaa29803351ca/src/main/java/org/datanucleus/store/rdbms/connectionpool/BoneCPConnectionPoolFactory.java#L74

The code above seems to be using the minPoolSize and maxPoolSize values to set the min and max setMinConnectionsPerPartition()/setMaxConnectionsPerPartition on the DataStore.

https://github.com/wwadge/bonecp/blob/74bc3287025fc137ca28909f0f7693edae37a15d/bonecp/src/main/java/com/jolbox/bonecp/BoneCPConfig.java#L64
https://github.com/wwadge/bonecp/blob/74bc3287025fc137ca28909f0f7693edae37a15d/bonecp/src/main/java/com/jolbox/bonecp/BoneCPConfig.java#L66
https://github.com/wwadge/bonecp/blob/74bc3287025fc137ca28909f0f7693edae37a15d/bonecp/src/main/java/com/jolbox/bonecp/BoneCPConfig.java#L70

So the default values for
partitionCount=1 (recommended value is 2-4 for partitionCount)
minConnectionsPerPartition=1
maxConnectionsPerPartitions=2 

So when using defaults across the board, we should only see a max of 2 connections to the backend DB. I am seeing 10 in my env and 14 in a customer env.
 
when minPoolSize=12, maxPoolSize=30, we should see a max of 30 connections, but we are seeing 42.
when minPoolSize=10, maxPooSize=15, we should see a max of 15 but we are seeing 20 even under no load scenarios.

Could you please explain the whats being enforced and whats not. Thanks

**Comment by andyjefferson** [comment]
The forum is for asking questions. Issue tracker is for raising issues with valid testcases. Thank you.

**Comment by nrg4878** [comment]
Apologies Andy, I wasnt sure where else to post. Could you mind pointing me where I need to post my question to? Thanks

**Comment by andyjefferson** [comment]
http://www.datanucleus.org/support.html
