### ISSUE TITLE
Basic ElementCollection Column configuration ignored

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-rdbms#86]
As can be seen in the example, the @Column is ignored for basic element collections which results in an  invalid index being generated for MySQL because the amount of bytes exceed the maximum allowed size.
[mysql-elementcollection.zip](https://github.com/datanucleus/datanucleus-rdbms/files/397427/mysql-elementcollection.zip)

**Comment by andyjefferson** [comment]
Dup of https://github.com/datanucleus/datanucleus-api-jpa/issues/32
